#!/usr/bin/env Rscript
##
## Regenerate R/r6_docs.R.
##
## Methods defined directly inside an R6Class() call are documented with normal
## roxygen comments next to the definition. The shared method lists in
## Common_functions.R are attached to the generators at run time by
## R6_set_list_of_items(), so roxygen never sees them there. This script emits
## one external documentation stanza per (class, method) pair for those, using
## the @eval / @R6method mechanism described in R/r6_doc.R.
##
## Run from the package root, against an installed copy of the package:
##
##     Rscript dev/generate_r6_docs.R
##
## then re-run devtools::document().

suppressMessages(library(hdf5r))
ns <- asNamespace("hdf5r")

## Use the working copy of the helpers, which may be newer than what is installed.
source("R/r6_doc.R")

## The shared lists whose methods are injected rather than written inline.
shared_lists <- c("interface", "commonFG", "commonFGT", "commonFGDT", "commonFGDTA")
shared_names <- unique(unlist(lapply(shared_lists, function(l) names(get(l, envir = ns)))))

generators <- Filter(
    function(x) inherits(x, "R6ClassGenerator"),
    mget(ls(ns, all.names = TRUE), envir = ns, ifnotfound = list(NULL))
)

pairs <- list()
for (cls in sort(names(generators))) {
    methods <- generators[[cls]]$public_methods
    for (m in sort(intersect(names(methods), shared_names))) {
        if (!is.function(methods[[m]])) next
        pairs[[length(pairs) + 1L]] <- c(cls, m)
    }
}

## Fail loudly rather than writing a file that will not document.
for (p in pairs) {
    tryCatch(
        r6_doc(p[1], p[2]),
        error = function(e) stop("r6_doc(\"", p[1], "\", \"", p[2], "\") failed: ",
                                 conditionMessage(e), call. = FALSE)
    )
}

lines <- c(
    "## Generated by dev/generate_r6_docs.R - do not edit by hand.",
    "##",
    "## Documentation for the methods that Common_functions.R attaches to the R6",
    "## generators at run time. roxygen cannot see a comment attached to those, so",
    "## each one gets an external @R6method block built from its docstrings. See",
    "## R/r6_doc.R for how the text is assembled.",
    ""
)
for (p in pairs) {
    lines <- c(lines, sprintf("#' @eval r6_doc(\"%s\", \"%s\")", p[1], p[2]), "NULL", "")
}

writeLines(lines, "R/r6_docs.R")
message("Wrote R/r6_docs.R with ", length(pairs), " stanzas.")
