ARG DEB_HDF5_IMG

FROM $DEB_HDF5_IMG

# copy the local context
USER docker
COPY --chown=docker:docker . /home/docker/hdf5r

ENTRYPOINT [ /bin/bash ]

ARG BUILD_OUTPUT
RUN cd /home/docker/hdf5r \
    && R CMD check ${BUILD_OUTPUT} || true

