ARG DEB_HDF5_IMG
FROM $DEB_HDF5_IMG

# copy the local context
USER docker
COPY --chown=docker:docker . /home/docker/hdf5r

ENTRYPOINT [ /bin/bash ]

RUN cd /home/docker/hdf5r \
    && R CMD build . \
    && R CMD check hdf5r_*.tar.gz
