## Generated by dev/generate_r6_docs.R - do not edit by hand.
##
## Documentation for the methods that Common_functions.R attaches to the R6
## generators at run time. roxygen cannot see a comment attached to those, so
## each one gets an external @R6method block built from its docstrings. See
## R/r6_doc.R for how the text is assembled.

#' @eval r6_doc("H5A", "flush")
NULL

#' @eval r6_doc("H5A", "get_filename")
NULL

#' @eval r6_doc("H5D", "attr_delete")
NULL

#' @eval r6_doc("H5D", "attr_delete_by_idx")
NULL

#' @eval r6_doc("H5D", "attr_delete_by_name")
NULL

#' @eval r6_doc("H5D", "attr_exists")
NULL

#' @eval r6_doc("H5D", "attr_exists_by_name")
NULL

#' @eval r6_doc("H5D", "attr_get_number")
NULL

#' @eval r6_doc("H5D", "attr_info_by_idx")
NULL

#' @eval r6_doc("H5D", "attr_info_by_name")
NULL

#' @eval r6_doc("H5D", "attr_name_by_idx")
NULL

#' @eval r6_doc("H5D", "attr_open")
NULL

#' @eval r6_doc("H5D", "attr_open_by_idx")
NULL

#' @eval r6_doc("H5D", "attr_open_by_name")
NULL

#' @eval r6_doc("H5D", "attr_rename")
NULL

#' @eval r6_doc("H5D", "attr_rename_by_name")
NULL

#' @eval r6_doc("H5D", "create_attr")
NULL

#' @eval r6_doc("H5D", "create_attr_by_name")
NULL

#' @eval r6_doc("H5D", "create_reference")
NULL

#' @eval r6_doc("H5D", "flush")
NULL

#' @eval r6_doc("H5D", "get_filename")
NULL

#' @eval r6_doc("H5D", "get_obj_name")
NULL

#' @eval r6_doc("H5D", "obj_info")
NULL

#' @eval r6_doc("H5File", "attr_delete")
NULL

#' @eval r6_doc("H5File", "attr_delete_by_idx")
NULL

#' @eval r6_doc("H5File", "attr_delete_by_name")
NULL

#' @eval r6_doc("H5File", "attr_exists")
NULL

#' @eval r6_doc("H5File", "attr_exists_by_name")
NULL

#' @eval r6_doc("H5File", "attr_get_number")
NULL

#' @eval r6_doc("H5File", "attr_info_by_idx")
NULL

#' @eval r6_doc("H5File", "attr_info_by_name")
NULL

#' @eval r6_doc("H5File", "attr_name_by_idx")
NULL

#' @eval r6_doc("H5File", "attr_open")
NULL

#' @eval r6_doc("H5File", "attr_open_by_idx")
NULL

#' @eval r6_doc("H5File", "attr_open_by_name")
NULL

#' @eval r6_doc("H5File", "attr_rename")
NULL

#' @eval r6_doc("H5File", "attr_rename_by_name")
NULL

#' @eval r6_doc("H5File", "commit")
NULL

#' @eval r6_doc("H5File", "create_attr")
NULL

#' @eval r6_doc("H5File", "create_attr_by_name")
NULL

#' @eval r6_doc("H5File", "create_dataset")
NULL

#' @eval r6_doc("H5File", "create_group")
NULL

#' @eval r6_doc("H5File", "create_reference")
NULL

#' @eval r6_doc("H5File", "exists")
NULL

#' @eval r6_doc("H5File", "flush")
NULL

#' @eval r6_doc("H5File", "get_filename")
NULL

#' @eval r6_doc("H5File", "get_obj_name")
NULL

#' @eval r6_doc("H5File", "group_info")
NULL

#' @eval r6_doc("H5File", "group_info_by_idx")
NULL

#' @eval r6_doc("H5File", "group_info_by_name")
NULL

#' @eval r6_doc("H5File", "link")
NULL

#' @eval r6_doc("H5File", "link_copy_from")
NULL

#' @eval r6_doc("H5File", "link_copy_to")
NULL

#' @eval r6_doc("H5File", "link_create_external")
NULL

#' @eval r6_doc("H5File", "link_create_hard")
NULL

#' @eval r6_doc("H5File", "link_create_soft")
NULL

#' @eval r6_doc("H5File", "link_delete")
NULL

#' @eval r6_doc("H5File", "link_delete_by_idx")
NULL

#' @eval r6_doc("H5File", "link_exists")
NULL

#' @eval r6_doc("H5File", "link_info")
NULL

#' @eval r6_doc("H5File", "link_info_by_idx")
NULL

#' @eval r6_doc("H5File", "link_move_from")
NULL

#' @eval r6_doc("H5File", "link_move_to")
NULL

#' @eval r6_doc("H5File", "link_name_by_idx")
NULL

#' @eval r6_doc("H5File", "link_value")
NULL

#' @eval r6_doc("H5File", "link_value_by_idx")
NULL

#' @eval r6_doc("H5File", "ls")
NULL

#' @eval r6_doc("H5File", "mount")
NULL

#' @eval r6_doc("H5File", "obj_copy_from")
NULL

#' @eval r6_doc("H5File", "obj_copy_to")
NULL

#' @eval r6_doc("H5File", "obj_info")
NULL

#' @eval r6_doc("H5File", "obj_info_by_idx")
NULL

#' @eval r6_doc("H5File", "obj_info_by_name")
NULL

#' @eval r6_doc("H5File", "open")
NULL

#' @eval r6_doc("H5File", "open_by_idx")
NULL

#' @eval r6_doc("H5File", "path_valid")
NULL

#' @eval r6_doc("H5File", "unmount")
NULL

#' @eval r6_doc("H5Group", "attr_delete")
NULL

#' @eval r6_doc("H5Group", "attr_delete_by_idx")
NULL

#' @eval r6_doc("H5Group", "attr_delete_by_name")
NULL

#' @eval r6_doc("H5Group", "attr_exists")
NULL

#' @eval r6_doc("H5Group", "attr_exists_by_name")
NULL

#' @eval r6_doc("H5Group", "attr_get_number")
NULL

#' @eval r6_doc("H5Group", "attr_info_by_idx")
NULL

#' @eval r6_doc("H5Group", "attr_info_by_name")
NULL

#' @eval r6_doc("H5Group", "attr_name_by_idx")
NULL

#' @eval r6_doc("H5Group", "attr_open")
NULL

#' @eval r6_doc("H5Group", "attr_open_by_idx")
NULL

#' @eval r6_doc("H5Group", "attr_open_by_name")
NULL

#' @eval r6_doc("H5Group", "attr_rename")
NULL

#' @eval r6_doc("H5Group", "attr_rename_by_name")
NULL

#' @eval r6_doc("H5Group", "commit")
NULL

#' @eval r6_doc("H5Group", "create_attr")
NULL

#' @eval r6_doc("H5Group", "create_attr_by_name")
NULL

#' @eval r6_doc("H5Group", "create_dataset")
NULL

#' @eval r6_doc("H5Group", "create_group")
NULL

#' @eval r6_doc("H5Group", "create_reference")
NULL

#' @eval r6_doc("H5Group", "exists")
NULL

#' @eval r6_doc("H5Group", "flush")
NULL

#' @eval r6_doc("H5Group", "get_filename")
NULL

#' @eval r6_doc("H5Group", "get_obj_name")
NULL

#' @eval r6_doc("H5Group", "group_info")
NULL

#' @eval r6_doc("H5Group", "group_info_by_idx")
NULL

#' @eval r6_doc("H5Group", "group_info_by_name")
NULL

#' @eval r6_doc("H5Group", "link")
NULL

#' @eval r6_doc("H5Group", "link_copy_from")
NULL

#' @eval r6_doc("H5Group", "link_copy_to")
NULL

#' @eval r6_doc("H5Group", "link_create_external")
NULL

#' @eval r6_doc("H5Group", "link_create_hard")
NULL

#' @eval r6_doc("H5Group", "link_create_soft")
NULL

#' @eval r6_doc("H5Group", "link_delete")
NULL

#' @eval r6_doc("H5Group", "link_delete_by_idx")
NULL

#' @eval r6_doc("H5Group", "link_exists")
NULL

#' @eval r6_doc("H5Group", "link_info")
NULL

#' @eval r6_doc("H5Group", "link_info_by_idx")
NULL

#' @eval r6_doc("H5Group", "link_move_from")
NULL

#' @eval r6_doc("H5Group", "link_move_to")
NULL

#' @eval r6_doc("H5Group", "link_name_by_idx")
NULL

#' @eval r6_doc("H5Group", "link_value")
NULL

#' @eval r6_doc("H5Group", "link_value_by_idx")
NULL

#' @eval r6_doc("H5Group", "ls")
NULL

#' @eval r6_doc("H5Group", "mount")
NULL

#' @eval r6_doc("H5Group", "obj_copy_from")
NULL

#' @eval r6_doc("H5Group", "obj_copy_to")
NULL

#' @eval r6_doc("H5Group", "obj_info")
NULL

#' @eval r6_doc("H5Group", "obj_info_by_idx")
NULL

#' @eval r6_doc("H5Group", "obj_info_by_name")
NULL

#' @eval r6_doc("H5Group", "open")
NULL

#' @eval r6_doc("H5Group", "open_by_idx")
NULL

#' @eval r6_doc("H5Group", "path_valid")
NULL

#' @eval r6_doc("H5Group", "unmount")
NULL

#' @eval r6_doc("H5RefClass", "dec_ref")
NULL

#' @eval r6_doc("H5RefClass", "get_file_id")
NULL

#' @eval r6_doc("H5RefClass", "get_obj_type")
NULL

#' @eval r6_doc("H5RefClass", "get_ref")
NULL

#' @eval r6_doc("H5RefClass", "inc_ref")
NULL

#' @eval r6_doc("H5T", "attr_delete")
NULL

#' @eval r6_doc("H5T", "attr_delete_by_idx")
NULL

#' @eval r6_doc("H5T", "attr_delete_by_name")
NULL

#' @eval r6_doc("H5T", "attr_exists")
NULL

#' @eval r6_doc("H5T", "attr_exists_by_name")
NULL

#' @eval r6_doc("H5T", "attr_get_number")
NULL

#' @eval r6_doc("H5T", "attr_info_by_idx")
NULL

#' @eval r6_doc("H5T", "attr_info_by_name")
NULL

#' @eval r6_doc("H5T", "attr_name_by_idx")
NULL

#' @eval r6_doc("H5T", "attr_open")
NULL

#' @eval r6_doc("H5T", "attr_open_by_idx")
NULL

#' @eval r6_doc("H5T", "attr_open_by_name")
NULL

#' @eval r6_doc("H5T", "attr_rename")
NULL

#' @eval r6_doc("H5T", "attr_rename_by_name")
NULL

#' @eval r6_doc("H5T", "create_attr")
NULL

#' @eval r6_doc("H5T", "create_attr_by_name")
NULL

#' @eval r6_doc("H5T", "create_reference")
NULL

#' @eval r6_doc("H5T", "get_obj_name")
NULL

#' @eval r6_doc("H5T", "obj_info")
NULL

